# Generated by Django 6.0 on 2025-12-12 21:01

import flight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=flight.models.air_image_upload_path),
        ),
    ]
