# Generated by Django 6.0 on 2025-12-12 21:17

import flight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_airplane_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=flight.models.air_image_upload_path),
        ),
        migrations.AddField(
            model_name='crew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=flight.models.crew_image_upload_path),
        ),
    ]
